levels = {};

levels.TEST = "\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
X___XXXXXXXXXXXXXXXXXXXXXXXXX\n\
X_P_______________XXXXXXXXXXX\n\
X___XXXXXXXXXXXXX_XXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXX_XXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXX_XXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXX_XXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXX_XXXXXXXXXXX\n\
XXXXXXXXXXXX____________XXXXX\n\
XXXXXXXXXXXX____________XXXXX\n\
XXXXXXXXXXXX____________XXXXX\n\
XXXXXXXXXXXX____________XXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
";