var levels = {};

var mklevels = function() {

levels.TEST = {}

levels.TEST.map = "\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
X___XXXXXXXXXXXXXXXXXXXXXXXXX\n\
X_P_______________XXXXXXXXXXX\n\
X___XXXXXXXXXXXXX_XXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXX_XXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXX_XXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXX_XXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXX_XXXXXXXXXXX\n\
XXXXXXXXXXXXX_________XXXXXXX\n\
XXXXXXXXXXXXX_________XXXXXXX\n\
XXXXXXXXXXXXX_________XXXXXXX\n\
XXXXXXXXXXXXX_________XXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n\
";

levels.TEST.mobs = [{X: 17, Y: 12, NAME: "wowman", PARTY: mobs.PARTY.DEMOCRAT, RANK: mobs.RANK.CONGRESSPERSON, ONDEFEAT: function(){} }];

}